Repository Murmele/Gittyup, pull requests merged in 2022-07, with the labels that each got.

#204 flathub badge
  README.md
Labels: documentation

#208 docs: updated README (build)
  README.md
Labels: question, macOS

#201 Fix crash when having errors while adding a remote account
  src/host/Account.cpp
  src/host/Account.h
  src/host/Beanstalk.cpp
  src/host/Bitbucket.cpp
  src/host/GitHub.cpp
  src/host/GitLab.cpp
Labels: bug

#224 Allow building Gittyup without building HTML docs
  dep/cmark/CMakeLists.txt
Labels: enhancement

#223 Fix crash when global GIT config is invalid
  src/app/Gittyup.cpp
  src/git/Config.cpp
Labels: bug
