Repository Murmele/Gittyup, pull requests merged in 2022-10, with the labels that each got.

#287 Fix ReferenceList
  src/ui/CMakeLists.txt
  src/ui/DiffView/FileWidget.cpp
  src/ui/ReferenceModel.cpp
  src/ui/ReferenceModel.h
  src/ui/ReferenceView.cpp
  test/CMakeLists.txt
  test/referencelist.cpp
Labels: bug

#297 Fix ReferenceList ctor invocations with missing filterCurrentCommit values
  src/dialogs/MergeDialog.cpp
  src/dialogs/MergeDialog.h
  src/dialogs/NewBranchDialog.cpp
  src/ui/CommitList.cpp
  src/ui/ReferenceList.cpp
  src/ui/ReferenceList.h
  src/ui/ReferenceModel.cpp
  src/ui/ReferenceModel.h
  src/ui/ReferenceView.cpp
  src/ui/ReferenceView.h
  src/ui/ReferenceWidget.cpp
  test/referencelist.cpp
Labels: bug

#295 Adds a setting to hide the menu bar and a global settings button.
  src/dialogs/SettingsDialog.cpp
  src/ui/MainWindow.cpp
  src/ui/MenuBar.cpp
  src/ui/MenuBar.h
  src/ui/ToolBar.cpp
  src/ui/ToolBar.h
Labels: enhancement

#298 Fix editor line when lines contain same content
  src/ui/DiffView/HunkWidget.cpp
  test/EditorLineInfos.cpp
  test/Test.h
  test/testRepos/.gitignore
  test/testRepos/16_LinestagingLineContent.zip
  test/testRepos/17_LinestagingLineContentStageAddedLine.zip
  test/testRepos/18_deleteLinesStagedLast.zip
Labels: bug

#301 Only show author override link when commit editor is visible
  src/ui/DetailView.cpp
  src/ui/DetailView.h
Labels: enhancement

#300 Improve SSH config handling
  src/git/Remote.cpp
  test/CMakeLists.txt
  test/SshConfig.cpp
  test/ssh_config
  test/ssh_config2
Labels: bug

#289 Ability to change dates in amend
  src/dialogs/AmendDialog.cpp
  src/dialogs/AmendDialog.h
  src/git/Repository.cpp
  src/git/Repository.h
  src/git/Signature.cpp
  src/git/Signature.h
  src/ui/DetailView.cpp
  src/ui/RepoView.cpp
  src/ui/RepoView.h
  test/amend.cpp
Labels: enhancement

#273 Implement Amend Dialog
  src/dialogs/AmendDialog.cpp
  src/dialogs/AmendDialog.h
  src/dialogs/CMakeLists.txt
  src/git/Commit.cpp
  src/git/Commit.h
  src/git/Repository.cpp
  src/git/Repository.h
  src/git/Signature.cpp
  src/git/Signature.h
  src/ui/CommitList.cpp
  src/ui/CommitList.h
  src/ui/DetailView.cpp
  src/ui/RepoView.cpp
  src/ui/RepoView.h
  test/CMakeLists.txt
  test/amend.cpp
  test/init_repo.cpp
Labels: enhancement

#313 Add Gitea Support
  cl-fmt.sh
  cmake-format.json
  rsrc/gitea.png
  rsrc/resources.qrc
  src/dialogs/AccountDialog.cpp
  src/host/Account.cpp
  src/host/Account.h
  src/host/Accounts.cpp
  src/host/CMakeLists.txt
  src/host/Gitea.cpp
  src/host/Gitea.h
Labels: enhancement

#317 Fix account type saving and loading
  src/host/Account.cpp
  src/host/Account.h
  src/host/Accounts.cpp
  src/ui/SideBar.cpp
  src/ui/TabWidget.cpp
Labels: bug

#319 Use constant instead of hard-coded literals for number of available account types
  .github/workflows/build.yml
  src/ui/SideBar.cpp
Labels: bug

#302 Add full file context menu to file tree / list
  src/ui/DiffTreeModel.cpp
  src/ui/DiffTreeModel.h
  src/ui/DoubleTreeWidget.cpp
  src/ui/DoubleTreeWidget.h
  src/ui/FileContextMenu.cpp
  src/ui/FileContextMenu.h
  src/ui/IgnoreDialog.cpp
  src/ui/IgnoreDialog.h
  src/ui/RepoView.cpp
  src/ui/TreeView.cpp
  src/ui/TreeView.h
  test/CMakeLists.txt
  test/TreeView.cpp
  test/fileContextMenu.cpp
  test/testRepos/TestRepository.zip
Labels: enhancement

#314 Fix AUR builds
  .github/workflows/build.yml
  CMakeLists.txt
  dep/cmark/CMakeLists.txt
  dep/git/CMakeLists.txt
  dep/hunspell/CMakeLists.txt
  dep/libgit2/CMakeLists.txt
  dep/libssh2/CMakeLists.txt
  dep/lua/CMakeLists.txt
  dep/openssl/CMakeLists.txt
  l10n/CMakeLists.txt
  pack/CMakeLists.txt
  pack/PKGBUILD
  pack/Readme.md
  pack/flatpak/Readme.md
  src/app/CMakeLists.txt
  src/conf/CMakeLists.txt
  src/conf/Settings.cpp
  src/update/UpdateDialog.cpp
  test/CMakeLists.txt
  test/CommitAuthorCommitter.cpp
  test/EditorLineInfos.cpp
  test/HunkWidget.cpp
  test/Submodule.cpp
  test/Test.cpp
  test/Test.h
  test/TreeView.cpp
  test/amend.cpp
  test/branches_panel.cpp
  test/init_repo.cpp
  test/rebase.cpp
  test/referencelist.cpp
Labels: bug, enhancement, flatpak, linux

#328 Publish persistent version on GitHub CI
  .github/workflows/build.yml
  README.md
  docs/index.md
Labels: bug

#333 Fix release tag creation
  .github/workflows/build.yml
Labels: bug

#340 Fix libssh2 build
  dep/libssh2/CMakeLists.txt
Labels: enhancement

#308 DiffView: Load patches on demand
  src/ui/DiffView/DiffView.cpp
  src/ui/DiffView/DiffView.h
Labels: enhancement
