Repository Murmele/Gittyup, pull requests merged in 2022-04, with the labels that each got.

#120 Add support for excluded patterns getting listed by `git lfs track`
  src/dialogs/ConfigDialog.cpp
  src/git/Repository.cpp
  src/git/Repository.h
Labels: bug

#122 Fix staging
  src/git/Patch.cpp
  src/git/Patch.h
  src/ui/DiffView/DiffView.cpp
  src/ui/DiffView/EditButton.cpp
  src/ui/DiffView/FileWidget.cpp
  src/ui/DiffView/FileWidget.h
  src/ui/DiffView/HunkWidget.cpp
  src/ui/DiffView/HunkWidget.h
  test/EditorLineInfos.cpp
  test/Test.cpp
  test/testRepos/13_singleHunkNoStaged.zip
Labels: bug

#127 Improve QT minimum version requirements
  .github/workflows/build.yml
  README.md
  src/git/Repository.cpp
Labels: bug, documentation

#132 remove label
  src/dialogs/SettingsDialog.cpp
Labels: bug, minor

#63 Open versioned file with default editor / Checkout the versioned file to a selected folder
  src/git/Commit.cpp
  src/git/Commit.h
  src/ui/FileContextMenu.cpp
  src/ui/FileContextMenu.h
  src/ui/RepoView.h
Labels: enhancement

#136 add screenshots
  README.md
  rsrc/TagCreation.png
  rsrc/dark.png
  rsrc/dark@2x.png
  rsrc/native.png
  rsrc/native@2x.png
  rsrc/resources.qrc
  rsrc/screenshots/CommitMessageTemplateEditor.png
  rsrc/screenshots/double_treeview_single_line_staging.png
  rsrc/screenshots/main_dark.png
  rsrc/screenshots/main_dark@2x.png
  rsrc/screenshots/main_dark_orig.png
  rsrc/screenshots/main_native.png
  rsrc/screenshots/main_native@2x.png
  rsrc/screenshots/main_native_orig.png
  rsrc/screenshots/main_show_commits_of_specific_file.png
  rsrc/screenshots/main_show_selected_branch.png
  rsrc/screenshots/main_split.png
  rsrc/screenshots/main_split.xcf
  rsrc/screenshots/main_split@2x.png
  rsrc/screenshots/main_split_orig.png
  rsrc/screenshots/starring_commits.png
  rsrc/screenshots/tag_selection.png
  rsrc/screenshots/treeview.png
  rsrc/system.png
Labels: documentation

#131 Fix Segmentation fault if file is removed and symlink created
  .github/workflows/build.yml
  src/git/Commit.cpp
  src/git/Repository.cpp
  src/ui/DiffTreeModel.cpp
Labels: bug

#145 Add github page
  README.md
  docs/_config.yml
  docs/acknowledgments.md
  docs/changelog.md
  docs/index.md
  docs/plugin.md
  docs/privacy.md
  rsrc/screenshots/CommitMessageTemplateEditor.png
  rsrc/screenshots/CommitMessageTemplateSelection.png
  src/app/CMakeLists.txt
Labels: documentation

#125 Release 1.1.0
  CMakeLists.txt
  README.md
  docs/index.md
  rsrc/linux/com.github.Murmele.Gittyup.appdata.xml
  src/update/Updater.cpp
Labels: documentation
