Repository Murmele/Gittyup, pull requests merged in 2022-12, with the labels that each got.

#366 Fix discarding complete content of the file and submodules
  CMakeLists.txt
  src/git/Patch.cpp
  src/ui/DoubleTreeWidget.cpp
  src/ui/FileContextMenu.cpp
  test/CMakeLists.txt
  test/EditorLineInfos.cpp
  test/TreeView.cpp
  test/fileContextMenu.cpp
  test/testRepos/19_discardCompleteDeletedContent.zip
  test/testRepos/20_discardCompleteAddedContent.zip
  test/testRepos/TestRepository.zip
Labels: bug, unittest_convered

#383 Replace settings strings by ids
  src/app/Application.cpp
  src/app/Theme.cpp
  src/conf/Setting.cpp
  src/conf/Setting.h
  src/conf/Settings.cpp
  src/conf/Settings.h
  src/cred/CredentialHelper.cpp
  src/dialogs/CommitDialog.cpp
  src/dialogs/CommitDialog.h
  src/dialogs/ConfigDialog.cpp
  src/dialogs/DiffPanel.cpp
  src/dialogs/MergeDialog.cpp
  src/dialogs/RemoteDialog.cpp
  src/dialogs/SettingsDialog.cpp
  src/dialogs/ThemeDialog.cpp
  src/editor/TextEditor.cpp
  src/tools/ShowTool.cpp
  src/ui/BlameMargin.cpp
  src/ui/CommitList.cpp
  src/ui/CommitToolBar.cpp
  src/ui/DiffView/FileWidget.cpp
  src/ui/DoubleTreeWidget.cpp
  src/ui/HotkeyManager.cpp
  src/ui/MainWindow.cpp
  src/ui/MenuBar.cpp
  src/ui/RemoteCallbacks.cpp
  src/ui/RepoView.cpp
  src/update/UpdateDialog.cpp
  src/update/Updater.cpp
  test/CommitAuthorCommitter.cpp
  test/Setting.cpp
  test/Submodule.cpp
Labels: enhancement

#400 Use customized flatpak builder Docker image
  .github/workflows/build.yml
  flatpak-builder/Dockerfile
Labels: bug, flatpak

#406 Do not let files steal focus from commit list
  src/ui/DoubleTreeWidget.cpp
Labels: bug
