Repository Murmele/Gittyup, pull requests merged in 2022-05, with the labels that each got.

#146 show image also when it was deleted in the commit
  src/ui/DiffView/Images.cpp
Labels: enhancement

#156 Don't trigger GitHub Actions for every push
  .github/workflows/build.yml
Labels: enhancement

#154 Improve windows app icon
  rsrc/Gittyup.ico
Labels: enhancement, minor

#155 Fix packaging for windows deploying old OpenSSL DLLs
  pack/CMakeLists.txt
Labels: bug, windows

#140 Show first diff in Diffview
  src/ui/DoubleTreeWidget.cpp
Labels: enhancement

#159 Fix check for 64 bit on Windows relying on MSVC
  pack/CMakeLists.txt
Labels: bug, windows

#160 use bundled zlib on win64 too
  .github/workflows/build.yml
Labels: bug, windows

#161 publish also mac release
  .github/workflows/build.yml
  README.md
  docs/index.md
Labels: enhancement, osx

#164 Fix publish github page only when tagging on master
  .github/workflows/build.yml
Labels: bug, documentation

#82 do tests before publishing
  .github/workflows/build.yml
  src/app/Application.cpp
  src/app/Application.h
  src/app/Theme.cpp
  test/CMakeLists.txt
  test/Diff.cpp
  test/Test.cpp
  test/Test.h
  test/bare_repo.cpp
  test/branches_panel.cpp
  test/index.cpp
  test/init_repo.cpp
  test/merge.cpp
  test/new_branch_dialog.cpp
  test/testRepos/gitahead-test.zip
Labels: enhancement

#172 hunks must be loaded before applying the patch
  src/ui/DiffView/HunkWidget.cpp
  src/ui/DiffView/HunkWidget.h
Labels: bug

#174 Matrix badge
  README.md
  src/dialogs/AboutDialog.cpp
Labels: documentation
