Repository Murmele/Gittyup, pull requests merged in 2022-09, with the labels that each got.

#260 Fixed the menubar color in Dark theme
  conf/themes/Dark.lua
Labels: bug

#257 Fix collapse counter
  src/ui/TreeView.cpp
  src/ui/TreeView.h
Labels: bug

#262 Canonicalize repository paths on Windows
  src/CMakeLists.txt
  src/conf/CMakeLists.txt
  src/conf/RecentRepositories.cpp
  src/conf/RecentRepositories.h
  src/git/CMakeLists.txt
  src/git/Repository.cpp
  src/util/CMakeLists.txt
  src/util/Path.cpp
  src/util/Path.h
  test/bare_repo.cpp
  test/init_repo.cpp
Labels: bug, windows

#242 Implement solving merge conflicts for whole files
  src/app/Theme.cpp
  src/app/Theme.h
  src/git/Patch.cpp
  src/git/Patch.h
  src/ui/DiffView/FileWidget.cpp
  src/ui/DiffView/FileWidget.h
  src/ui/DiffView/HunkWidget.cpp
Labels: enhancement

#184 implement keypress otherwise a segfault occurs
  src/ui/TreeView.cpp
  src/ui/TreeView.h
Labels: bug

#270 Fix new branch dialog showing the wrong starting point
  src/dialogs/NewBranchDialog.cpp
  src/ui/ReferenceView.cpp
Labels: bug

#271 Fix reference view
  src/ui/ReferenceList.cpp
  src/ui/ReferenceView.cpp
Labels: bug

#245 Fix updater not closing all main windows
  CMakeLists.txt
  src/update/CMakeLists.txt
  src/update/UpdateDialog.cpp
  src/update/Updater.cpp
Labels: bug

#278 Also show full file conflict solving buttons when there's no hunks
  src/ui/DiffView/FileWidget.cpp
Labels: bug

#281 Branding updates
  pack/CMakeLists.txt
  rsrc/background.png
  rsrc/dmg-background.png
  rsrc/dmg-background.svg
  rsrc/logo-type_light-textobj.svg
  rsrc/logo-type_light.svg
Labels: enhancement

#280 Fix load selection
  src/ui/DoubleTreeWidget.cpp
  src/ui/TreeView.cpp
  test/CMakeLists.txt
  test/TreeView.cpp
  test/testRepos/TreeViewCollapseCount.zip
Labels: bug, unittest_convered

#288 Improve Terminal detection on macOS
  src/ui/RepoView.cpp
Labels: bug

#286 Improve handling of full file merge conflicts
  docs/changelog.md
  src/ui/DiffView/FileWidget.cpp
Labels: enhancement

#292 Use different repository as module, because the other one was deleted
  test/Submodule.cpp
  test/testRepos/SubmoduleTest.zip
Labels: bug
