Repository Murmele/Gittyup, pull requests merged in 2022-06, with the labels that each got.

#162 add windows test
  .github/workflows/build.yml
  src/git/Patch.cpp
  src/git/Patch.h
  src/ui/DiffView/FileWidget.cpp
  test/CMakeLists.txt
  test/EditorLineInfos.cpp
  test/Test.cpp
  test/testRepos/14_windowsCRLF.zip
  test/testRepos/15_windowsCRLF_multipleHunks.zip
Labels: bug, windows

#176 Automate appdata release notes
  .github/workflows/build.yml
  cmake/generate_appdata.cmake
  rsrc/linux/com.github.Murmele.Gittyup.appdata.xml.in
  src/app/CMakeLists.txt
Labels: documentation

#173 Use original author and email when cherry picking and reverting a commit
  src/git/Repository.cpp
  src/git/Repository.h
  src/ui/DetailView.cpp
  src/ui/RepoView.cpp
  src/ui/RepoView.h
  test/CMakeLists.txt
  test/CommitAuthorCommitter.cpp
  test/testRepos/CherryPickAuthorEmail.zip
Labels: bug

#197 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#192 Fix dead links in README.md
  README.md
  docs/index.md
Labels: documentation

#202 Remove unused but automatically started HTTP server for GitHub authentication
  src/host/Account.h
  src/host/GitHub.cpp
Labels: enhancement

#203 Use official name for macOS
  .github/workflows/build.yml
  README.md
  docs/changelog.md
  docs/index.md
  pack/CMakeLists.txt
  src/app/Application.cpp
  src/editor/ScintillaQt.cpp
  src/update/Updater.cpp
  test/editor.cpp
Labels: documentation, macOS
