Repository Murmele/Gittyup, pull requests merged in 2023-01, with the labels that each got.

#253 change startup wmclass
  rsrc/linux/com.github.Murmele.Gittyup.desktop
Labels: bug, flatpak

#411 Fix submodule/conflicted files not visible
  src/ui/DiffTreeModel.cpp
  test/TreeView.cpp
  test/testRepos/ConflictedAndStagedFile.zip
  test/testRepos/DirtySubmoduleUnstagedTree.zip
Labels: bug, unittest_convered

#412 return if initializing a rebase fails.
  src/git/Repository.cpp
  src/ui/RepoView.cpp
Labels: bug

#437 fix #398
  src/dialogs/AmendDialog.cpp
  test/amend.cpp
Labels: unittest_convered

#441 Fix used wrong config in ConfigDialog.cpp
  src/dialogs/ConfigDialog.cpp
  src/dialogs/DeleteBranchDialog.cpp
  src/dialogs/DiffPanel.cpp
  src/dialogs/RemoteDialog.cpp
  src/git/Branch.cpp
  src/git/Remote.cpp
  src/git/Repository.cpp
  src/git/Repository.h
  src/git/Submodule.cpp
  src/ui/DetailView.cpp
  src/ui/RepoView.cpp
  test/Test.cpp
Labels: bug, enhancement

#443 Flatpakdisableupdate
  .github/workflows/build.yml
  CMakeLists.txt
  src/update/UpdateDialog.cpp
Labels: enhancement

#444 Fix executing external diff with flatpak
  src/tools/DiffTool.cpp
  src/tools/MergeTool.cpp
Labels: bug

#413 Implement automatic usage of template in commit message
  src/ui/CMakeLists.txt
  src/ui/CommitEditor.cpp
  src/ui/CommitEditor.h
  src/ui/DetailView.cpp
  src/ui/TemplateButton.cpp
  src/ui/TemplateButton.h
  src/ui/TemplateDialog.cpp
  src/ui/TemplateDialog.h
  test/CMakeLists.txt
  test/commitEditor.cpp
  test/commitMessageTemplate.cpp
Labels: enhancement

#415 colorized badges
  conf/themes/Dark.lua
  conf/themes/Default.lua
  docs/changelog.md
  src/app/CustomTheme.cpp
  src/app/Theme.cpp
  src/app/Theme.h
  src/log/LogDelegate.cpp
  src/ui/Badge.cpp
  src/ui/Badge.h
  src/ui/CommitList.cpp
  src/ui/DetailView.cpp
  src/ui/DiffView/FileWidget.cpp
  src/ui/ViewDelegate.cpp
Labels: enhancement

#347 Credential store
  src/conf/Setting.cpp
  src/conf/Setting.h
  src/cred/CMakeLists.txt
  src/cred/CredentialHelper.cpp
  src/cred/CredentialHelper.h
  src/cred/Store.cpp
  src/cred/Store.h
  src/dialogs/SettingsDialog.cpp
  test/CMakeLists.txt
  test/Test.cpp
  test/store.cpp
Labels: enhancement
