Repository Murmele/Gittyup, pull requests merged in 2023-02, with the labels that each got.

#464 Fix credential helper setting not loading custom helpers
  src/dialogs/SettingsDialog.cpp
Labels: bug

#463 Fetch hunk as needed new
  src/ui/DiffView/DiffView.cpp
  src/ui/DiffView/DiffView.h
  src/ui/DiffView/FileWidget.cpp
  src/ui/DiffView/FileWidget.h
Labels: enhancement

#439 * Fix local installation paths on Linux, see issue #393
  dep/git/CMakeLists.txt
  pack/CMakeLists.txt
  src/app/CMakeLists.txt
  src/index/CMakeLists.txt
  src/update/CMakeLists.txt
Labels: bug, linux

#397 Fix cmake installation paths
  .github/workflows/build.yml
  CMakeLists.txt
  dep/scintilla/CMakeLists.txt
  docs/changelog.md
  docs/index.md
  l10n/CMakeLists.txt
  pack/CMakeLists.txt
  rsrc/Info.plist.in
  rsrc/github-repository-open-graph-Gittyup.png.xmp
  rsrc/linux/com.github.Murmele.Gittyup.appdata.xml.in
  rsrc/linux/com.github.Murmele.Gittyup.desktop
  src/app/Application.cpp
  src/app/CMakeLists.txt
  src/conf/CMakeLists.txt
  src/conf/Settings.cpp
  src/conf/Settings.h
  src/index/CMakeLists.txt
  src/update/CMakeLists.txt
Labels: enhancement

#470 Implement search function for the TreeView
  docs/changelog.md
  src/ui/TreeWidget.cpp
  src/ui/TreeWidget.h
Labels: enhancement

#306 Speedup refreshing
  CMakeLists.txt
  src/CMakeLists.txt
  src/conf/Settings.cpp
  src/git/Commit.cpp
  src/git/Commit.h
  src/git/Diff.cpp
  src/git/Repository.h
  src/tools/CMakeLists.txt
  src/tools/MergeTool.cpp
  src/trace.h
  src/ui/CommitList.cpp
  src/ui/CommitList.h
  src/ui/DiffView/DiffView.cpp
  src/ui/DiffView/HunkWidget.cpp
  src/ui/DoubleTreeWidget.cpp
  src/ui/DoubleTreeWidget.h
  src/ui/FileContextMenu.cpp
  src/ui/MainWindow.cpp
  src/ui/ReferenceModel.cpp
  src/ui/ReferenceWidget.cpp
  src/ui/ReferenceWidget.h
  src/ui/RepoView.cpp
  src/ui/RepoView.h
  src/ui/TreeView.cpp
  src/update/Updater.cpp
  src/util/CMakeLists.txt
  src/util/Debug.h
  src/util/Path.cpp
  test/EditorLineInfos.cpp
  test/Test.cpp
  test/bare_repo.cpp
  test/fileContextMenu.cpp
  test/init_repo.cpp
  test/rebase.cpp
Labels: enhancement

#454 Add features to documentation
  docs/changelog.md
  docs/index.md
  rsrc/screenshots/ColorizedBadges.png
Labels: documentation
